// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_onboarding.sql

package queries

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  first_name,
  last_name,
  date_of_birth,
  gender,
  email,
  phone_number,
  aadhaar_number,
  pan_number,
  address,
  city,
  state,
  pincode,
  kyc_status,
  customer_status
)
VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING
  id,
  customer_code,
  first_name,
  last_name,
  email,
  phone_number,
  date_of_birth,
  gender,
  kyc_status,
  customer_status,
  created_at
`

type CreateCustomerParams struct {
	FirstName      string
	LastName       string
	DateOfBirth    sql.NullTime
	Gender         sql.NullString
	Email          sql.NullString
	PhoneNumber    sql.NullString
	AadhaarNumber  sql.NullString
	PanNumber      sql.NullString
	Address        sql.NullString
	City           sql.NullString
	State          sql.NullString
	Pincode        sql.NullString
	KycStatus      sql.NullString
	CustomerStatus sql.NullString
}

type CreateCustomerRow struct {
	ID             int32
	CustomerCode   sql.NullString
	FirstName      string
	LastName       string
	Email          sql.NullString
	PhoneNumber    sql.NullString
	DateOfBirth    sql.NullTime
	Gender         sql.NullString
	KycStatus      sql.NullString
	CustomerStatus sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CreateCustomerRow, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Email,
		arg.PhoneNumber,
		arg.AadhaarNumber,
		arg.PanNumber,
		arg.Address,
		arg.City,
		arg.State,
		arg.Pincode,
		arg.KycStatus,
		arg.CustomerStatus,
	)
	var i CreateCustomerRow
	err := row.Scan(
		&i.ID,
		&i.CustomerCode,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.KycStatus,
		&i.CustomerStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createKYCDocument = `-- name: CreateKYCDocument :one
INSERT INTO kyc_documents (
  customer_id,
  document_type,
  document_number,
  document_file_path,
  verification_status
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, document_type, document_number, verification_status, created_at
`

type CreateKYCDocumentParams struct {
	CustomerID         int32
	DocumentType       sql.NullString
	DocumentNumber     sql.NullString
	DocumentFilePath   sql.NullString
	VerificationStatus sql.NullString
}

type CreateKYCDocumentRow struct {
	ID                 int32
	CustomerID         int32
	DocumentType       sql.NullString
	DocumentNumber     sql.NullString
	VerificationStatus sql.NullString
	CreatedAt          sql.NullTime
}

func (q *Queries) CreateKYCDocument(ctx context.Context, arg CreateKYCDocumentParams) (CreateKYCDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, createKYCDocument,
		arg.CustomerID,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.DocumentFilePath,
		arg.VerificationStatus,
	)
	var i CreateKYCDocumentRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.VerificationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
UPDATE customers
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCustomer(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCustomer, id)
	return err
}

const getCustomerByAadhaar = `-- name: GetCustomerByAadhaar :one
SELECT
  id,
  customer_code,
  first_name,
  last_name,
  email,
  phone_number,
  aadhaar_number,
  kyc_status,
  customer_status
FROM customers
WHERE aadhaar_number = $1 AND deleted_at IS NULL
`

type GetCustomerByAadhaarRow struct {
	ID             int32
	CustomerCode   sql.NullString
	FirstName      string
	LastName       string
	Email          sql.NullString
	PhoneNumber    sql.NullString
	AadhaarNumber  sql.NullString
	KycStatus      sql.NullString
	CustomerStatus sql.NullString
}

func (q *Queries) GetCustomerByAadhaar(ctx context.Context, aadhaarNumber sql.NullString) (GetCustomerByAadhaarRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByAadhaar, aadhaarNumber)
	var i GetCustomerByAadhaarRow
	err := row.Scan(
		&i.ID,
		&i.CustomerCode,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.AadhaarNumber,
		&i.KycStatus,
		&i.CustomerStatus,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT
  id,
  customer_code,
  first_name,
  last_name,
  email,
  phone_number,
  date_of_birth,
  gender,
  address,
  city,
  state,
  pincode,
  kyc_status,
  customer_status,
  created_at,
  updated_at
FROM customers
WHERE id = $1 AND deleted_at IS NULL
`

type GetCustomerByIDRow struct {
	ID             int32
	CustomerCode   sql.NullString
	FirstName      string
	LastName       string
	Email          sql.NullString
	PhoneNumber    sql.NullString
	DateOfBirth    sql.NullTime
	Gender         sql.NullString
	Address        sql.NullString
	City           sql.NullString
	State          sql.NullString
	Pincode        sql.NullString
	KycStatus      sql.NullString
	CustomerStatus sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) GetCustomerByID(ctx context.Context, id int32) (GetCustomerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerCode,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.City,
		&i.State,
		&i.Pincode,
		&i.KycStatus,
		&i.CustomerStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCustomers = `-- name: ListActiveCustomers :many
SELECT
  id,
  customer_code,
  first_name,
  last_name,
  phone_number,
  email,
  kyc_status,
  customer_status,
  created_at
FROM customers
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveCustomersParams struct {
	Limit  int32
	Offset int32
}

type ListActiveCustomersRow struct {
	ID             int32
	CustomerCode   sql.NullString
	FirstName      string
	LastName       string
	PhoneNumber    sql.NullString
	Email          sql.NullString
	KycStatus      sql.NullString
	CustomerStatus sql.NullString
	CreatedAt      sql.NullTime
}

func (q *Queries) ListActiveCustomers(ctx context.Context, arg ListActiveCustomersParams) ([]ListActiveCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCustomersRow
	for rows.Next() {
		var i ListActiveCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerCode,
			&i.FirstName,
			&i.LastName,
			&i.PhoneNumber,
			&i.Email,
			&i.KycStatus,
			&i.CustomerStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKYCDocumentsByCustomer = `-- name: ListKYCDocumentsByCustomer :many
SELECT
  id,
  document_type,
  document_number,
  document_file_path,
  verification_status,
  created_at
FROM kyc_documents
WHERE customer_id = $1
ORDER BY created_at DESC
`

type ListKYCDocumentsByCustomerRow struct {
	ID                 int32
	DocumentType       sql.NullString
	DocumentNumber     sql.NullString
	DocumentFilePath   sql.NullString
	VerificationStatus sql.NullString
	CreatedAt          sql.NullTime
}

func (q *Queries) ListKYCDocumentsByCustomer(ctx context.Context, customerID int32) ([]ListKYCDocumentsByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, listKYCDocumentsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKYCDocumentsByCustomerRow
	for rows.Next() {
		var i ListKYCDocumentsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.DocumentFilePath,
			&i.VerificationStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomersByName = `-- name: SearchCustomersByName :many
SELECT
  id,
  customer_code,
  first_name,
  last_name,
  email,
  phone_number,
  kyc_status,
  customer_status
FROM customers
WHERE deleted_at IS NULL
  AND (
    first_name ILIKE '%' || $1 || '%'
    OR last_name ILIKE '%' || $1 || '%'
  )
ORDER BY first_name
LIMIT $2 OFFSET $3
`

type SearchCustomersByNameParams struct {
	Column1 sql.NullString
	Limit   int32
	Offset  int32
}

type SearchCustomersByNameRow struct {
	ID             int32
	CustomerCode   sql.NullString
	FirstName      string
	LastName       string
	Email          sql.NullString
	PhoneNumber    sql.NullString
	KycStatus      sql.NullString
	CustomerStatus sql.NullString
}

func (q *Queries) SearchCustomersByName(ctx context.Context, arg SearchCustomersByNameParams) ([]SearchCustomersByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCustomersByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCustomersByNameRow
	for rows.Next() {
		var i SearchCustomersByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerCode,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.KycStatus,
			&i.CustomerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerKYCStatus = `-- name: UpdateCustomerKYCStatus :exec
UPDATE customers
SET
  kyc_status = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCustomerKYCStatusParams struct {
	ID        int32
	KycStatus sql.NullString
}

func (q *Queries) UpdateCustomerKYCStatus(ctx context.Context, arg UpdateCustomerKYCStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerKYCStatus, arg.ID, arg.KycStatus)
	return err
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :exec
UPDATE customers
SET
  customer_status = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCustomerStatusParams struct {
	ID             int32
	CustomerStatus sql.NullString
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerStatus, arg.ID, arg.CustomerStatus)
	return err
}
