// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Customer struct {
	ID             int32
	CustomerCode   sql.NullString
	FirstName      string
	LastName       string
	DateOfBirth    sql.NullTime
	Gender         sql.NullString
	Email          sql.NullString
	PhoneNumber    sql.NullString
	AadhaarNumber  sql.NullString
	PanNumber      sql.NullString
	Address        sql.NullString
	City           sql.NullString
	State          sql.NullString
	Pincode        sql.NullString
	KycStatus      sql.NullString
	CustomerStatus sql.NullString
	DeletedAt      sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type KycDocument struct {
	ID                 int32
	CustomerID         int32
	DocumentType       sql.NullString
	DocumentNumber     sql.NullString
	DocumentFilePath   sql.NullString
	VerificationStatus sql.NullString
	CreatedAt          sql.NullTime
}
